// Generated by ts-to-zod
import { z } from 'zod';

export const characterSchema = z.object({
	name: z.string(),
	role: z.union([
		z.literal('protagonist'),
		z.literal('antagonist'),
		z.literal('mentor'),
		z.literal('supporting'),
		z.literal('narrator')
	]),
	description: z.string(),
	emotions: z.array(z.string()),
	position: z.union([
		z.literal('left'),
		z.literal('center'),
		z.literal('right'),
		z.literal('background'),
		z.literal('foreground')
	])
});

export const slideTextSchema = z.object({
	dialogue: z.array(
		z.object({
			character: z.string(),
			line: z.string()
		})
	),
	onScreenText: z.string().optional()
});

export const slideSchema = z.object({
	slideId: z.number(),
	timestamp: z.string(),
	durationSeconds: z.number(),
	sceneTitle: z.string(),
	text: slideTextSchema,
	characters: z.array(characterSchema),
	sceneDescription: z.string(),
	visualStyle: z.string(),
	cameraAngle: z.string()
});

export const storyMetadataSchema = z.object({
	title: z.string(),
	totalDuration: z.string(),
	genre: z.string(),
	style: z.string(),
	targetAudience: z.string()
});

export const storySchema = z.object({
	storyMetadata: storyMetadataSchema,
	slides: z.array(slideSchema)
});
