import dotenv from 'dotenv';
dotenv.config();

import { StateGraph } from '@langchain/langgraph';
import { ChatOpenAI } from '@langchain/openai';
import { ChatPromptTemplate } from '@langchain/core/prompts';
import OpenAI from 'openai';
import { addLog } from '$lib/server/storyboardLogStore';
import type { Project, VisualSlide } from '$lib/models/project.model';
import type { StoryOutline } from '$lib/models/story';
import { storyOutlineSchema } from '$lib/schemas/story.schema.js'; // Generated by ts-to-zod
import { updateStream } from '$lib/streams';

const llm = new ChatOpenAI({
	modelName: 'gpt-4',
	temperature: 0
}).withStructuredOutput(storyOutlineSchema);

const openai = new OpenAI({
	apiKey: process.env.OPENAI_API_KEY
});

// Node Functions
const generateStoryOutline = async (project: Project): Promise<Partial<Project>> => {
	console.log('[LangGraph] generateStoryOutline called with:', project.prompts);
	addLog(`[LangGraph] generateStoryOutline called with: ${project.prompts}`);
	const prompt = ChatPromptTemplate.fromTemplate(`
Create a detailed storyboard structure for: {concept}

Requirements:
- Create exactly {numSlides} slides
- Include specific character descriptions for visual generation
- Provide clear narration and/or dialogue for each slide
- Describe the visual scene in detail for image generation
- Specify camera angles and visual style
- Ensure story flows logically from slide to slide
- Calculate accurate timestamps for each slide

Target audience: {targetAudience}
Story style: {storyStyle}
Genre: {genre}
`);

	const chain = prompt.pipe(llm);

	type ChainInput = Parameters<typeof chain.invoke>[0];
	const storyOutLine = (await chain.invoke(project.prompts as ChainInput));

	// Initialize visual slides structure
	const slides: VisualSlide[] = storyOutLine.slideOutlines.map((part, index) => ({
		slideNumber: index + 1,
		imageGenerated: false
	}));

	console.log('[LangGraph] generateStoryOutline result:\n', JSON.stringify(storyOutLine, null, 2));
	addLog(`[LangGraph] generateStoryOutline result: ${JSON.stringify(storyOutLine, null, 2)}`);
	return {
		currentSlide: 1,
		visualSlides: slides
	};
};

const generateImagePrompt = (slide: VisualSlide): string => {
	const promptParts: string[] = [];

	// Add scene description
	promptParts.push(`Scene: ${slide.sceneDescription}`);

	// Add character descriptions
	const characterNames: string[] = [];
	slide.characters.forEach((char) => {
		characterNames.push(char.name);
		let charDesc = `${char.name}: ${char.description}, positioned ${char.position}`;
		if (char.emotions.length > 0) {
			charDesc += `, expressing ${char.emotions.join(', ')}`;
		}
		promptParts.push(charDesc);
	});

	// Add visual style and camera
	promptParts.push(`Visual style: ${slide.visualStyle}`);
	promptParts.push(`Camera angle: ${slide.cameraAngle}`);

	const fullPrompt = `Storyboard panel: ${promptParts.join('. ')}. Professional illustration style, clean lines, suitable for storyboard presentation.`;
	return fullPrompt;
};

const generateImage = async (project: Project): Promise<Partial<Project>> => {
	console.log('[LangGraph] generateImage called for slide :', project.currentSlide);
	addLog(`[LangGraph] generateImage called for prompt: ${project.currentSlide}`);

	let visualSlide: VisualSlide = project.visualSlides[project.currentSlide];

	//create prompt for image generation
	const imagePrompt = generateImagePrompt(visualSlide);

	try {
		const response = await openai.images.generate({
			model: 'dall-e-3',
			prompt: imagePrompt,
			size: '1792x1024', // Landscape format good for storyboards
			quality: 'standard',
			n: 1
		});

		const imageUrl = response.data && response.data[0] && response.data[0].url;

		visualSlide.imageGenerated = true;
		visualSlide.imagePrompt = imagePrompt; //TODO: do we actually want to store the image prompt for DALL-E?
		visualSlide.imageUrl = imageUrl;

		const updatedVisualSlides = [...project.visualSlides];
		updatedVisualSlides[project.currentSlide - 1] = visualSlide;

		if (imageUrl) {
			console.log('[LangGraph] generateImage result:', imageUrl);
			addLog(`[LangGraph] generateImage result: ${imageUrl}`);
		} else {
			console.log('[LangGraph] generateImage failed');
			addLog('[LangGraph] generateImage failed');
		}
		return {
			visualSlides: updatedVisualSlides
		};
	} catch (error) {
		addLog(`Image generation failed:', ${error}`);
		return {};
	}
};

const saveSlideAndAdvance = async (project: Project): Promise<Partial<Project>> => {
	console.log('[LangGraph] saveSlideAndAdvance called for slide:', project.currentSlide);
	addLog(`[LangGraph] saveSlideAndAdvance called for slide: ${project.currentSlide}`);

	const currentSlideNum = project.currentSlide;

	// Advance to next slide. mark complete is in the logic of shouldContinue()
	const nextSlide = currentSlideNum + 1;

	console.log('[LangGraph] saveSlideAndAdvance nextSlide:', nextSlide);
	addLog(`[LangGraph] saveSlideAndAdvance nextSlide: ${nextSlide}`);

	updateStream(project._id.toString(), { project });

	return {
		currentSlide: nextSlide
	};
};

const shouldContinue = (project: Project): 'nextSlide' | 'complete' => {
	return project.currentSlide && project.currentSlide <= project.totalSlide
		? 'nextSlide'
		: 'complete';
};

// Build the Graph
export const createStoryboardGraph = () => {
	console.log('[LangGraph] createStoryboardGraph called');
	addLog('[LangGraph] createStoryboardGraph called');
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	const workflow = new StateGraph<Project, any, any, string>({
		channels: {
			userConcept: null,
			storyOutline: null,
			currentSlide: null,
			visualSlides: null,
			generationReady: null,
			generatedImages: null
		}
	});

	// Add nodes
	workflow.addNode('generateStoryOutline', generateStoryOutline);
	workflow.addNode('generateImage', generateImage);
	workflow.addNode('saveAndAdvance', saveSlideAndAdvance);

	// Define edges using '__start__' and '__end__' as required
	workflow.addEdge('__start__', 'generateStoryOutline');
	workflow.addEdge('generateStoryOutline', 'generateImage');
	workflow.addEdge('generateImage', 'saveAndAdvance');
	workflow.addConditionalEdges('saveAndAdvance', shouldContinue, {
		nextSlide: 'generateImage',
		complete: '__end__'
	});

	return workflow.compile();
};

// Main execution function
export const runStoryboardCreation = async (project: Project): Promise<void> => {
	console.log('[LangGraph] runStoryboardCreation called with:', project.prompts);
	addLog(`[LangGraph] runStoryboardCreation called with: ${project.prompts}`);
	const app = createStoryboardGraph();

	const result = await app.invoke(project);
	console.log('[LangGraph] runStoryboardCreation result:', result);
	addLog(`[LangGraph] runStoryboardCreation result: ${JSON.stringify(result)}`);
};

// // Interactive Functions for UI Integration
// export const getCurrentSlideDraft = (state: StoryboardState): SlideContent | null => {
// 	return state.currentSlideDraft;
// };

// export const submitRefinementFeedback = (
// 	state: StoryboardState,
// 	feedback: string
// ): Partial<StoryboardState> => {
// 	return { refinementFeedback: feedback };
// };

// export const approveSlideForGeneration = (): Partial<StoryboardState> => {
// 	return { generationReady: true };
// };
